function tabelaLatex(vec1, vec2, ID)

fprintf(ID,['\\begin{table}[tbp]\n'...
            '\\begin{center}\n'...
            '\\caption{Relatório Comparativo de estratégias}\n'...
            '\\label{tab:relat}\n'...
            '\\begin{tabular}{l|r|r}\n'...
            '\\hline Estratégia de entrada & Sistema Inteligente & Sistema Classico\\\\ \n']);
fprintf(ID, '\\hline Instrumento usado: & %s & %s\\\\ \n',vec1{1}, vec2{1});
fprintf(ID, '\\hline Granularidade: & %s & %s\\\\ \n',vec1{2}, vec2{2});
fprintf(ID, '\\hline Data de inicio: & %s & %s\\\\ \n \\hline Data de termino: & %s & %s\\\\ \n '...
    ,vec1{3}, vec2{3},vec1{4}, vec2{4});
fprintf(ID, '\\hline Lucro Total: & R\\$ %.2f  & R\\$ %.2f \\\\ \n \\hline Lucro Bruto: &  R\\$ %.2f  &  R\\$ %.2f \\\\ \n \\hline Prejuízo Bruto: &  R\\$ %.2f  &  R\\$ %.2f \\\\ \n',...
    vec1{5}, vec2{5},vec1{6}, vec2{6},vec1{7}, vec2{7});
fprintf(ID, '\\hline Fator de Lucro: & %.2f & %.2f\\\\ \n\\hline Número Total de Operações: & %d & %d\\\\ \n',...
    vec1{8}, vec2{8},vec1{9}, vec2{9});
fprintf(ID, '\\hline Percentual de Vencedoras: & %.2f \\%% & %.2f \\%% \\\\ \n \\hline Operações Vencedoras: &%d&%d\\\\ \n',...
    vec1{10}, vec2{10},vec1{11}, vec2{11});
fprintf(ID, '\\hline Operações Perdedoras: &%d&%d\\\\ \n\\hline Lucro Médio Total: & R\\$ %.2f & R\\$ %.2f \\\\ \n',...
    vec1{12}, vec2{12},vec1{13}, vec2{13});
fprintf(ID, '\\hline Lucro Médio das Vencedoras: & R\\$ %.2f & R\\$ %.2f \\\\ \n\\hline Prejuízo Médio das Perdedoras:  & R\\$ %.2f & R\\$ %.2f \\\\ \n',...
    vec1{14}, vec2{14},vec1{15}, vec2{15});
fprintf(ID, '\\hline Razão Média Vencedoras/Média Perdedoras: & %.2f & %.2f\\\\ \n \\hline Maior Operação Vencedora: &  R\\$ %.2f  &  R\\$ %.2f \\\\ \n',...
        vec1{16}, vec2{16},vec1{17}, vec2{17});
fprintf(ID, '\\hline Pior Operação Perdedora: &  R\\$ %.2f  &  R\\$ %.2f \\\\ \n\\hline Maior Número de Vitórias Consecutivas: & %d & %d\\\\ \n',...
        vec1{18}, vec2{18},vec1{19}, vec2{19});
fprintf(ID, '\\hline Maior Número de Derrotas Consecutivas: & %d &%d\\\\ \n \\hline Média de Tempo das Operações: & %.2f & %.2f\\\\ \n',...
        vec1{20}, vec2{20},vec1{21}, vec2{21});
fprintf(ID, '\\hline Média de Tempo das Operações Vencedoras: & %.2f & %.2f \\\\ \n \\hline Média de Tempo das Operações Perdedoras: &%.2f  & %.2f\\\\ \n',...
        vec1{22}, vec2{22},vec1{23}, vec2{23});
fprintf(ID, '\\hline Sharpe Ratio: & %f &  %f \\\\ \n',vec1{24}, vec2{24});
fprintf(ID, '\\hline Estrategia Buy and Hold no mesmo periodo: &  R\\$ %.2f  &  R\\$ %.2f  \\\\ \n',vec1{25}, vec2{25});
fprintf(ID, ['\\hline'...
                     '\\end{tabular}'...
                    '\\end{center}'...
                    '\\end{table}']);
end